"""CC4: rp5deck.theme_colour - the companion's system-carousel background
colour should match the installed ES theme instead of hard-coded BLACK.

Fixtures (tests/fixtures/cc4-*):
  - cc4-pistation-x-theme-xml-real-capture-2026-09-24.xml            REAL,
    unmodified, fetched from
    https://github.com/JandersonJS/es-theme-PiStation-X/blob/377efd8/theme.xml
    (commit 377efd83a224d54dce090eea5016655029a440bd, 2026-09-24) - the
    device's installed theme (companion.py Resolver.system_logo() already
    fetches paths under ".../themes/es-theme-PiStation-X/..."). Chosen
    over a trimmed excerpt specifically because it is NOT well-formed XML
    (one comment closes with "--->" instead of "-->", line 552) - the same
    class of bug as the "XML comment cannot hold --" memory note - so a
    parser that only works on a hand-cleaned excerpt would prove nothing.
  - cc4-pistation-x-colors-blue-real-capture-2026-09-24.xml            REAL,
    same repo/commit, main/colors/blue.xml - one of ten alternate colour
    variants (blue/brawn/cyan/gray/green/orange/red/silver/violet/yellow).
  - cc4-pistation-x-infos-gba-real-capture-2026-09-24.xml              REAL,
    same repo/commit, infos/gba.xml - one of 419 per-system include files
    theme.xml pulls in via `<include>./infos/${system.theme}.xml</include>`;
    proves this theme has NO per-system colour override (only text).
  - cc4-pistation-x-systemview-reflected-real-capture-2026-09-24.xml    REAL,
    same repo/commit, main/systemview/reflected.xml - the carousel/logo
    layout default_exclude_box()'s fractions are derived from
    (<carousel><pos>0 0.39</pos><size>1 0.3925</size></carousel>).
  - cc4-dp1-*-synthetic.png                                     SYNTHETIC,
    generated by this test file's own PNG encoder (see _encode_png below),
    never captured from a real screen.

Run: `python -B -m unittest tests.test_theme_colour -v` (no native libs -
this module has zero cairo/pango/PIL dependency, importable on Windows).
"""
import os
import statistics
import struct
import subprocess
import sys
import unittest
import zlib

HERE = os.path.dirname(os.path.abspath(__file__))
RP5DECK = os.path.dirname(HERE)
FIXTURES = os.path.join(HERE, "fixtures")
sys.path.insert(0, RP5DECK)

import theme_colour as tc  # noqa: E402


def _fixture(name):
    with open(os.path.join(FIXTURES, name), "r", encoding="utf-8-sig", errors="replace") as f:
        return f.read()


def _fixture_bytes(name):
    with open(os.path.join(FIXTURES, name), "rb") as f:
        return f.read()


def _encode_png(w, h, pixel_fn):
    """Test-only PNG encoder (colour type 6, RGBA8, filter-none scanlines)
    - the mirror image of theme_colour.decode_png, used only to build
    SYNTHETIC screenshot fixtures. Production code never encodes a PNG."""
    raw = bytearray()
    for y in range(h):
        raw.append(0)
        for x in range(w):
            r, g, b, a = pixel_fn(x, y)
            raw += bytes([r, g, b, a])

    def chunk(ctype, data):
        c = ctype + data
        return struct.pack(">I", len(data)) + c + struct.pack(">I", zlib.crc32(c) & 0xFFFFFFFF)

    ihdr = struct.pack(">IIBBBBB", w, h, 8, 6, 0, 0, 0)
    out = tc._PNG_SIG
    out += chunk(b"IHDR", ihdr)
    out += chunk(b"IDAT", zlib.compress(bytes(raw), 9))
    out += chunk(b"IEND", b"")
    return out


# ---------------------------------------------------------------------------
# Colour helpers
# ---------------------------------------------------------------------------
class TestColourHelpers(unittest.TestCase):
    def test_hex_to_rgb_6_and_8_digit(self):
        self.assertEqual(tc.hex_to_rgb("ffffff"), (1.0, 1.0, 1.0, 1.0))
        self.assertEqual(tc.hex_to_rgb("000000"), (0.0, 0.0, 0.0, 1.0))
        r, g, b, a = tc.hex_to_rgb("081622")
        self.assertAlmostEqual(r, 8 / 255.0)
        self.assertAlmostEqual(g, 0x16 / 255.0)
        self.assertAlmostEqual(b, 0x22 / 255.0)
        self.assertEqual(a, 1.0)
        _, _, _, a8 = tc.hex_to_rgb("FAFAFFB0")
        self.assertAlmostEqual(a8, 0xB0 / 255.0)

    def test_hex_to_rgb_accepts_leading_hash(self):
        self.assertEqual(tc.hex_to_rgb("#ffffff"), (1.0, 1.0, 1.0, 1.0))

    def test_hex_to_rgb_rejects_garbage(self):
        for bad in (None, "", "zz0000", "12345", "not-a-colour"):
            with self.assertRaises(ValueError):
                tc.hex_to_rgb(bad)

    def test_contrast_text_is_readable_both_directions(self):
        white_text = tc.contrast_text_color((0.05, 0.05, 0.05, 1.0))
        black_text = tc.contrast_text_color((0.95, 0.95, 0.95, 1.0))
        self.assertGreater(tc._luminance(white_text), 0.8)
        self.assertLess(tc._luminance(black_text), 0.2)


# ---------------------------------------------------------------------------
# (a) Theme XML parsing - against the REAL, not-well-formed theme.xml
# ---------------------------------------------------------------------------
# _FixtureTheme and _real_theme() removed: _real_theme() read
# tests/fixtures/cc4-pistation-x-{theme-xml,infos-gba,colors-blue}-real-
# capture-2026-09-24.xml, all real files fetched from the installed ES theme
# on the device, dropped from the public release (see
# DROPPED-FIXTURES-list.txt). Removed along with every test that used it
# (directly, or via _real_theme()) - see TestThemeXmlRealCapture below. No
# synthetic equivalent exists for a real, imperfectly-formed theme.xml.


class TestThemeXmlRealCapture(unittest.TestCase):
    """Proves the parser survives the REAL theme.xml (malformed comment and
    all) and reads the values a human checking the file by eye would see."""

    # test_malformed_comment_does_not_break_the_parser,
    # test_root_variables_match_the_real_file_by_eye,
    # test_lang_fr_variables_block_is_not_merged,
    # test_subset_dot_colorset_variable_does_not_eat_the_file,
    # test_infos_gba_has_no_colour_override,
    # test_include_chain_pulls_in_infos_gba,
    # test_include_chain_uses_a_different_system,
    # test_theme_background_color_for_gba,
    # test_theme_background_color_same_for_every_system,
    # test_colorset_overlay_changes_the_answer, and
    # test_unknown_colorset_falls_back_to_theme_default removed: all read
    # one of the cc4-pistation-x-*-real-capture-2026-09-24.xml fixtures
    # (directly or via _real_theme()), dropped from the public release (see
    # DROPPED-FIXTURES-list.txt). The remaining tests below exercise the
    # same functions' general mechanisms against hand-built XML instead, and
    # are unaffected.

    def test_per_system_view_background_wins_when_a_theme_has_one(self):
        # PiStation-X doesn't (proven above); this proves the GENERAL
        # mechanism for a theme that does.
        text = ('<theme><view name="system" system="genesis,megadrive">'
                '<image name="background"><color>112233</color></image>'
                '</view></theme>')
        self.assertEqual(tc.per_system_background(text, "genesis"), "112233")
        self.assertEqual(tc.per_system_background(text, "megadrive"), "112233")
        self.assertIsNone(tc.per_system_background(text, "gba"))

    def test_find_theme_root_from_a_logo_path(self):
        logo = "/storage/roms/themes/es-theme-PiStation-X/main/logos/gba.png"

        def isfile(p):
            return p.replace("\\", "/") == "/storage/roms/themes/es-theme-PiStation-X/theme.xml"

        root = tc.find_theme_root(logo, isfile=isfile)
        self.assertEqual(root.replace("\\", "/"), "/storage/roms/themes/es-theme-PiStation-X")

    def test_find_theme_root_missing_theme_xml_returns_none(self):
        self.assertIsNone(tc.find_theme_root("/nowhere/main/logos/gba.png", isfile=lambda p: False))

    def test_find_theme_root_empty_path(self):
        self.assertIsNone(tc.find_theme_root("", isfile=lambda p: True))

    def test_theme_background_color_missing_theme_xml_is_none_not_a_crash(self):
        self.assertIsNone(tc.theme_background_color("NOWHERE", "gba",
                                                      read=lambda p: (_ for _ in ()).throw(OSError()),
                                                      isfile=lambda p: False))


# ---------------------------------------------------------------------------
# PNG decode (pure Python, no cairo/PIL)
# ---------------------------------------------------------------------------
class TestPngDecode(unittest.TestCase):
    def test_round_trip_solid_colour(self):
        data = _fixture_bytes("cc4-dp1-solid-8x6-synthetic.png")
        w, h, rgba = tc.decode_png(data)
        self.assertEqual((w, h), (8, 6))
        self.assertEqual(len(rgba), 8 * 6 * 4)
        self.assertEqual(tuple(rgba[0:4]), (10, 140, 150, 255))
        self.assertEqual(tuple(rgba[-4:]), (10, 140, 150, 255))

    def test_round_trip_with_filters_sub_up_average_paeth(self):
        # A gradient exercises every byte-to-byte relationship the PNG
        # filters react to (constant rows would only ever pick filter 0).
        def px(x, y):
            return ((x * 7) % 256, (y * 11) % 256, (x + y) % 256, 255)

        data = _encode_png(16, 16, px)
        w, h, rgba = tc.decode_png(data)
        self.assertEqual((w, h), (16, 16))
        for y in (0, 5, 15):
            for x in (0, 5, 15):
                o = (y * w + x) * 4
                self.assertEqual(tuple(rgba[o:o + 4]), px(x, y))

    def test_bad_signature_raises_pngerror_not_a_crash(self):
        with self.assertRaises(tc.PngError):
            tc.decode_png(b"not a png at all")

    def test_truncated_data_raises_pngerror(self):
        data = _fixture_bytes("cc4-dp1-solid-8x6-synthetic.png")
        with self.assertRaises(tc.PngError):
            tc.decode_png(data[:40])

    def test_unsupported_colour_type_raises_pngerror(self):
        # Colour type 3 (palette) is explicitly unsupported.
        ihdr = struct.pack(">IIBBBBB", 1, 1, 8, 3, 0, 0, 0)

        def chunk(ctype, data):
            c = ctype + data
            return struct.pack(">I", len(data)) + c + struct.pack(">I", zlib.crc32(c) & 0xFFFFFFFF)

        data = tc._PNG_SIG + chunk(b"IHDR", ihdr) + chunk(b"IDAT", zlib.compress(b"\x00\x00")) + chunk(b"IEND", b"")
        with self.assertRaises(tc.PngError):
            tc.decode_png(data)


# ---------------------------------------------------------------------------
# (b) Median border colour, and the "excludes the logo" proof
# ---------------------------------------------------------------------------
class TestMedianBorderColour(unittest.TestCase):
    def test_uniform_image_returns_that_colour(self):
        w, h, rgba = tc.decode_png(_fixture_bytes("cc4-dp1-solid-8x6-synthetic.png"))
        r, g, b, a = tc.median_border_colour(w, h, rgba)
        self.assertAlmostEqual(r, 10 / 255.0, places=3)
        self.assertAlmostEqual(g, 140 / 255.0, places=3)
        self.assertAlmostEqual(b, 150 / 255.0, places=3)

    def test_exclusion_box_covering_everything_returns_none(self):
        w, h, rgba = tc.decode_png(_fixture_bytes("cc4-dp1-solid-8x6-synthetic.png"))
        self.assertIsNone(tc.median_border_colour(w, h, rgba, exclude_box=(0, 0, w, h)))

    def test_default_exclude_box_keeps_the_logo_band_out_of_the_scene_fixture(self):
        # cc4-dp1-border-vs-logo-200x120-synthetic.png: everywhere inside
        # default_exclude_box(200, 120) is blue ("logo/carousel"), every-
        # thing else is the true border colour (210, 90, 40).
        data = _fixture_bytes("cc4-dp1-border-vs-logo-200x120-synthetic.png")
        w, h, rgba = tc.decode_png(data)
        box = tc.default_exclude_box(w, h)
        r, g, b, a = tc.median_border_colour(w, h, rgba, exclude_box=box)
        self.assertAlmostEqual(r, 210 / 255.0, places=2)
        self.assertAlmostEqual(g, 90 / 255.0, places=2)
        self.assertAlmostEqual(b, 40 / 255.0, places=2)

    def test_break_it_without_exclusion_the_answer_is_wrong(self):
        """Prove-a-check-by-breaking-it: cc4-dp1-majority-contamination
        has "logo" blue covering the top 60% of rows (which is MORE than
        half of every sampled edge strip, top+left+right combined) and
        true red only in the bottom 40%. Without an exclude_box the
        (correct, robust-to-a-minority-of-noise) median gets outvoted and
        answers blue - proving the exclusion argument is actually load-
        bearing, not a no-op default."""
        data = _fixture_bytes("cc4-dp1-majority-contamination-40x40-synthetic.png")
        w, h, rgba = tc.decode_png(data)
        broken = tc.median_border_colour(w, h, rgba, exclude_box=None, band_frac=0.1)
        fixed = tc.median_border_colour(w, h, rgba, exclude_box=(0, 0, 40, 24), band_frac=0.1)
        self.assertGreater(broken[2], broken[0])   # blue-dominant: B > R
        self.assertGreater(fixed[0], fixed[2])     # red-dominant:  R > B
        self.assertNotEqual(broken, fixed)

    # test_default_exclude_box_matches_the_real_carousel_geometry removed:
    # depended on tests/fixtures/cc4-pistation-x-systemview-reflected-real-
    # capture-2026-09-24.xml, dropped from the public release (see
    # DROPPED-FIXTURES-list.txt).


# ---------------------------------------------------------------------------
# grim capture wrapper - timeout / failure never raise
# ---------------------------------------------------------------------------
class TestCaptureDp1(unittest.TestCase):
    def test_success_returns_stdout_bytes(self):
        def fake_run(cmd, capture_output, timeout):
            self.assertEqual(cmd, tc.DEFAULT_GRIM_CMD)
            self.assertEqual(timeout, 2.0)

            class R:
                returncode = 0
                stdout = b"\x89PNGfakebytes"
            return R()

        self.assertEqual(tc.capture_dp1(run=fake_run), b"\x89PNGfakebytes")

    def test_timeout_returns_none_not_a_raise(self):
        def fake_run(cmd, capture_output, timeout):
            raise subprocess.TimeoutExpired(cmd, timeout)

        self.assertIsNone(tc.capture_dp1(run=fake_run, timeout=0.01))

    def test_missing_binary_returns_none(self):
        def fake_run(cmd, capture_output, timeout):
            raise FileNotFoundError("no grim")

        self.assertIsNone(tc.capture_dp1(run=fake_run))

    def test_nonzero_exit_returns_none(self):
        def fake_run(cmd, capture_output, timeout):
            class R:
                returncode = 1
                stdout = b""
            return R()

        self.assertIsNone(tc.capture_dp1(run=fake_run))


# ---------------------------------------------------------------------------
# should_sample - "never while a game runs"
# ---------------------------------------------------------------------------
class TestShouldSample(unittest.TestCase):
    def test_sample_source_gated_off_during_a_game(self):
        self.assertTrue(tc.should_sample("sample", running=False))
        self.assertFalse(tc.should_sample("sample", running=True))

    def test_break_it_a_broken_gate_would_sample_during_a_game(self):
        """The 'never sample during a game' rule is THIS ONE LINE
        (`source == "sample" and not running`) - break it exactly as a
        careless edit would (drop the running check) and confirm the
        control notices, per the repo's break/restore convention."""
        def broken_should_sample(source, running):
            return source == "sample"           # BROKEN: ignores `running`

        self.assertTrue(broken_should_sample("sample", running=True))     # the bug
        self.assertFalse(tc.should_sample("sample", running=True))        # the real function catches it

    def test_theme_and_off_sources_never_sample(self):
        for running in (False, True):
            self.assertFalse(tc.should_sample("theme", running=running))
            self.assertFalse(tc.should_sample("off", running=running))


# ---------------------------------------------------------------------------
# SettleGate - debounce for fast carousel scrolling
# ---------------------------------------------------------------------------
class TestSettleGate(unittest.TestCase):
    def test_fires_once_after_settling(self):
        g = tc.SettleGate(settle_s=0.4)
        g.note("gba", 0.0)
        self.assertIsNone(g.ready(0.39))
        self.assertEqual(g.ready(0.40), "gba")
        self.assertIsNone(g.ready(0.41))            # already consumed

    def test_rapid_scrolling_only_fires_for_the_last_system(self):
        g = tc.SettleGate(settle_s=0.4)
        g.note("gba", 0.0)
        self.assertIsNone(g.ready(0.3))
        g.note("snes", 0.1)                          # scrolled again before settling
        self.assertIsNone(g.ready(0.3))
        g.note("nes", 0.2)                            # and again
        self.assertIsNone(g.ready(0.3))
        self.assertIsNone(g.ready(0.5))               # 0.2 + 0.4 = 0.6, not yet
        self.assertEqual(g.ready(0.6), "nes")          # only the LAST scroll fires
        self.assertIsNone(g.ready(0.65))

    def test_break_it_without_debounce_every_scroll_tick_would_fire(self):
        """A naive "sample on every event" implementation (no gate at all)
        would capture 3 times for 3 scroll ticks; SettleGate must reduce
        that to exactly 1 capture for the settled system."""
        g = tc.SettleGate(settle_s=0.4)
        ticks = [("gba", 0.0), ("snes", 0.05), ("nes", 0.10), ("snes9x", 0.15)]
        naive_capture_count = len(ticks)              # what "no debounce" would cost
        fires = []
        for system, t in ticks:
            g.note(system, t)
            r = g.ready(t)
            if r is not None:
                fires.append(r)
        # nothing fires mid-burst (each note() restarts the window)
        self.assertEqual(fires, [])
        # only after the burst ends and settle_s elapses:
        last_t = ticks[-1][1]
        self.assertEqual(g.ready(last_t + 0.4), "snes9x")
        self.assertEqual(len(fires) + 1, 1)
        self.assertLess(1, naive_capture_count)

    def test_cancel_clears_a_pending_note(self):
        g = tc.SettleGate(settle_s=0.4)
        g.note("gba", 0.0)
        g.cancel()
        self.assertIsNone(g.ready(1.0))


# ---------------------------------------------------------------------------
# SampleCache - glue: capture, cache per system, never raise
# ---------------------------------------------------------------------------
class TestSampleCache(unittest.TestCase):
    def _cache_with_fixed_scene(self):
        data = _fixture_bytes("cc4-dp1-border-vs-logo-200x120-synthetic.png")
        return tc.SampleCache(capture=lambda: data)

    def test_capture_caches_per_system(self):
        cache = self._cache_with_fixed_scene()
        self.assertIsNone(cache.cached("gba"))
        result = cache.capture("gba")
        self.assertIsNotNone(result)
        self.assertEqual(cache.captures, 1)
        self.assertEqual(cache.cached("gba"), result)
        self.assertIsNone(cache.cached("snes"))       # a different system: no cross-talk

    def test_capture_failure_returns_none_and_does_not_cache(self):
        cache = tc.SampleCache(capture=lambda: None)
        self.assertIsNone(cache.capture("gba"))
        self.assertIsNone(cache.cached("gba"))
        self.assertEqual(cache.captures, 0)

    def test_decode_failure_returns_none_and_does_not_cache(self):
        cache = tc.SampleCache(capture=lambda: b"not a png")
        self.assertIsNone(cache.capture("gba"))
        self.assertIsNone(cache.cached("gba"))

    def test_forget_clears_one_or_all(self):
        cache = self._cache_with_fixed_scene()
        cache.capture("gba")
        cache.capture("snes")
        cache.forget("gba")
        self.assertIsNone(cache.cached("gba"))
        self.assertIsNotNone(cache.cached("snes"))
        cache.forget()
        self.assertIsNone(cache.cached("snes"))

    def test_uses_the_default_exclude_box_by_default(self):
        # The scene fixture's only "correct" answer (border colour, not
        # the logo blue) is reachable exactly when SampleCache applies
        # default_exclude_box - if it didn't, this would come back blue.
        cache = self._cache_with_fixed_scene()
        bg, fg = cache.capture("gba")
        self.assertGreater(bg[0], bg[2])       # red channel > blue channel


if __name__ == "__main__":
    unittest.main()
